# Generated by Django 4.2 on 2023-07-01 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否已经删除')),
                ('tag', models.CharField(max_length=50, unique=True, verbose_name='题目标签')),
                ('nid', models.CharField(max_length=20, verbose_name='编号')),
            ],
            options={
                'db_table': 'shuatiapp_Tag',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否已经删除')),
                ('username', models.CharField(max_length=100, unique=True, verbose_name='用户名')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='邮箱')),
                ('detail', models.TextField(blank=True, null=True, verbose_name='个人简介')),
            ],
            options={
                'db_table': 'shuatiapp_User',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否已经删除')),
                ('question_id', models.CharField(max_length=20, verbose_name='题目编号')),
                ('question_content', models.TextField(verbose_name='题目内容')),
                ('options', models.JSONField(verbose_name='题目选项\n                     {\n                         "A":"选项1",\n                         "B":"选项2",\n                         "C":"选项3",\n                         "D":"选项4",\n                         "E":"选项5",\n                     }\n                     ')),
                ('correct_answer', models.CharField(max_length=20, verbose_name='正确答案')),
                ('tag', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='问题的标签', to='shuati_app.tag', verbose_name='题目标签')),
            ],
            options={
                'db_table': 'shuatiapp_Question',
            },
        ),
        migrations.CreateModel(
            name='ErrorBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否已经删除')),
                ('answer', models.CharField(max_length=100, verbose_name='用户的选项')),
                ('is_correct', models.BooleanField(verbose_name='是否回答正确')),
                ('detail', models.TextField(blank=True, null=True, verbose_name='笔记')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='错题本的题目', to='shuati_app.question', verbose_name='题目')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='错题本的用户', to='shuati_app.user', verbose_name='用户')),
            ],
            options={
                'db_table': 'shuatiapp_ErrorBook',
            },
        ),
        migrations.CreateModel(
            name='AnswerRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否已经删除')),
                ('answer', models.CharField(max_length=100, verbose_name='用户的选项')),
                ('is_correct', models.BooleanField(verbose_name='是否回答正确')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='答题记录的题目', to='shuati_app.question', verbose_name='题目')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='答题记录的用户', to='shuati_app.user', verbose_name='用户')),
            ],
            options={
                'db_table': 'shuatiapp_AnswerRecord',
            },
        ),
    ]
