# Generated by Django 4.2 on 2023-07-02 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shuati_app', '0002_adminuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='tag',
            field=models.CharField(max_length=50, verbose_name='题目标签'),
        ),
    ]
