# Generated by Django 4.2 on 2023-07-03 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shuati_app', '0004_alter_answerrecord_create_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer_detail',
            field=models.TextField(default='', verbose_name='题目解析'),
        ),
    ]
