# Generated by Django 4.2 on 2023-07-06 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shuati_app', '0005_question_answer_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerrecord',
            name='isInErrorBook',
            field=models.BooleanField(default=False, verbose_name='是否在错题本'),
        ),
        migrations.AddField(
            model_name='answerrecord',
            name='record_id',
            field=models.CharField(default='', max_length=20, verbose_name='题目编号'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='answer_detail',
            field=models.TextField(default='无', verbose_name='题目解析'),
        ),
        migrations.DeleteModel(
            name='ErrorBook',
        ),
    ]
